using System.Globalization;
using Schgen.Core.Placement;
using Schgen.Core.Yaml;

namespace Schgen.Core.KiCad;

/// Writes a hierarchical KiCad 10 schematic from a CircuitDocument + SchPlacement.
///
/// Output files (in <outDir>):
///   <project>.kicad_pro      project metadata
///   <project>.kicad_sch      root sheet (one per CircuitDocument)
///   <sheetName>.kicad_sch    one per non-root sheet referenced via root.instantiate
///
/// Per-pin rendering: a tiny wire stub from the pin endpoint outward, terminated
/// in either a hierarchical sheet pin (templates), global label (power nets and
/// cross-sheet singletons), local label (otherwise), or no_connect marker (NC).
public sealed partial class SchematicEmitter
{
    private readonly CircuitDocument _doc;
    private readonly LibraryIndex _libs;
    private readonly SchPlacement _placement;
    private readonly Dictionary<string, List<NetEndpoint>> _nets;
    private readonly HashSet<string> _flaggedNets;
    private readonly Dictionary<string, int> _instanceCounts;

    private const string KicadVersion = "20260306";
    private string _projectName = "";
    private string _rootUuid = "";
    private readonly List<SExpr> _pendingSheetLabels = new();
    private readonly double _pageCenterX;
    private readonly double _pageCenterY;
    private readonly bool _flattenSingleton;

    public SchematicEmitter(CircuitDocument doc, LibraryIndex libs, SchPlacement placement)
    {
        _doc = doc;
        _libs = libs;
        _placement = placement;
        _nets = Validator.CollectNetsToPins(doc, libs);
        _instanceCounts = doc.Root.Instantiate
            .GroupBy(i => i.Sheet)
            .ToDictionary(g => g.Key, g => g.Count(), StringComparer.Ordinal);
        _flaggedNets = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (net, ends) in _nets)
        {
            // Stubs generated by `host:` are aliases for placement, not
            // electrical rails - the actual rail (which they multi-net with
            // at the host pin) carries the PWR_FLAG. Flagging the stub too
            // would relabel it global, defeating its purpose of being an
            // anchor-eligible (single-sheet, single-UC) net.
            if (doc.GeneratedStubNets.Contains(net)) continue;
            bool needsFlag = ends.Any(e => e.Pin.Type == PinType.PowerIn)
                             && !ends.Any(e => e.Pin.Type == PinType.PowerOut || e.Pin.Type == PinType.Output);
            if (needsFlag) _flaggedNets.Add(net);
        }

        (_pageCenterX, _pageCenterY) = PageDimensions(doc.Config.PageSize);

        // If there's exactly one singleton sheet instantiated once at the
        // root, skip the hierarchical wrapping - the schematic is a single
        // flat page and the user doesn't need to click through a sub-sheet.
        _flattenSingleton =
            doc.Sheets.Count == 1
            && doc.Root.Instantiate.Count == 1
            && doc.Sheets.Values.Single().Template == false;
    }

    /// (centerX, centerY) in mm for KiCad's named page sizes, snapped to the
    /// 1.27 mm (50-mil) schematic grid so emitted pin endpoints stay on-grid.
    /// Used to offset all emitted coordinates so the placement region lands
    /// inside the printable area instead of clinging to the (0,0) sheet corner.
    private static (double, double) PageDimensions(string pageSize)
    {
        var dims = pageSize.ToUpperInvariant() switch
        {
            "A0"        => (1189.0, 841.0),
            "A1"        => (841.0, 594.0),
            "A2"        => (594.0, 420.0),
            "A3"        => (420.0, 297.0),
            "A4"        => (297.0, 210.0),
            "A5"        => (210.0, 148.0),
            "USLETTER"  => (279.4, 215.9),
            "USLEGAL"   => (355.6, 215.9),
            "USLEDGER"  => (431.8, 279.4),
            _           => (297.0, 210.0),
        };
        const double grid = 1.27;
        return (Math.Round(dims.Item1 * 0.5 / grid) * grid,
                Math.Round(dims.Item2 * 0.5 / grid) * grid);
    }

    public void Write(string outDir, string projectName)
    {
        Directory.CreateDirectory(outDir);
        _projectName = projectName;
        _rootUuid = NewUuid("root");

        if (_flattenSingleton)
        {
            // Single page: the root .kicad_sch IS the sheet, no children.
            var (onlyName, onlySheet) = _doc.Sheets.Single();
            var path = Path.Combine(outDir, $"{projectName}.kicad_sch");
            File.WriteAllText(path, EmitSheet(onlyName, onlySheet, asRoot: true).Format());
        }
        else
        {
            foreach (var (sheetName, sheet) in _doc.Sheets)
            {
                var path = Path.Combine(outDir, $"{sheetName}.kicad_sch");
                File.WriteAllText(path, EmitSheet(sheetName, sheet, asRoot: false).Format());
            }
            var rootPath = Path.Combine(outDir, $"{projectName}.kicad_sch");
            File.WriteAllText(rootPath, EmitRoot(projectName).Format());
        }

        var proPath = Path.Combine(outDir, $"{projectName}.kicad_pro");
        File.WriteAllText(proPath, EmitProject(projectName));

        // Project-level sym-lib-table so KiCad can resolve stock symbol
        // references (Device:C, Regulator_Switching:TLV62080DSGx, etc.) that
        // we deliberately did NOT embed in the .kicad_sch. Uses the
        // ${KICAD10_SYMBOL_DIR} variable that KiCad sets at runtime, so the
        // table works on any machine with KiCad 10 installed.
        var symLibPath = Path.Combine(outDir, "sym-lib-table");
        File.WriteAllText(symLibPath, EmitSymLibTable());
    }

    /// Any net that has a power_in endpoint and no power_out / output driver
    /// needs a PWR_FLAG to silence the "power pin not driven" ERC. Flag once,
    /// on the sheet that has the most endpoints (or the lexicographic-first
    /// sheet on a tie). This catches both declared power_nets and per-pin
    /// dedicated stubs like VBUS_5V_U1_1.
    private List<string> FlaggedPowerNetsOnSheet(string sheetName)
    {
        var flagged = new List<string>();
        foreach (var (net, ends) in _nets)
        {
            // Generated host: stub nets never get a PWR_FLAG - the rail
            // they alias does. See note in the ctor's _flaggedNets build.
            if (_doc.GeneratedStubNets.Contains(net)) continue;
            bool needsFlag = ends.Any(e => e.Pin.Type == PinType.PowerIn)
                             && !ends.Any(e => e.Pin.Type == PinType.PowerOut || e.Pin.Type == PinType.Output);
            if (!needsFlag) continue;

            // Pick a single home sheet for the flag so we don't double-stamp.
            var homeSheet = ends
                .GroupBy(e => e.Sheet)
                .OrderByDescending(g => g.Count())
                .ThenBy(g => g.Key, StringComparer.Ordinal)
                .First().Key;
            if (homeSheet == sheetName) flagged.Add(net);
        }
        flagged.Sort(StringComparer.Ordinal);
        return flagged;
    }

    private SList EmitPwrFlagLibSymbol()
    {
        // Mirrors KiCad's stock `power:PWR_FLAG` symbol:
        //   - (power global) marks it as a global power symbol.
        //   - Pin NAME is empty (""). Critical: KiCad uses a power symbol's
        //     pin name as its net binding. A non-empty name (e.g. "pwr")
        //     silently joins every PWR_FLAG instance to a single "pwr" net,
        //     triggering Power-output↔Power-output ERC errors across the
        //     entire design (the symptom that exposed this bug).
        //   - Sub-symbol naming uses the `_0_0` (pin) / `_0_1` (graphics)
        //     convention from KiCad's stock library.
        return new SList(
            SAtom.Sym("symbol"),
            SAtom.Str("power:PWR_FLAG"),
            new SList(SAtom.Sym("power"), SAtom.Sym("global")),
            new SList(SAtom.Sym("pin_numbers"), new SList(SAtom.Sym("hide"), SAtom.Sym("yes"))),
            new SList(SAtom.Sym("pin_names"),
                new SList(SAtom.Sym("offset"), SAtom.Num(0)),
                new SList(SAtom.Sym("hide"), SAtom.Sym("yes"))),
            new SList(SAtom.Sym("exclude_from_sim"), SAtom.Sym("no")),
            new SList(SAtom.Sym("in_bom"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("on_board"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("in_pos_files"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("duplicate_pin_numbers_are_jumpers"), SAtom.Sym("no")),
            EmitProperty("Reference", "#FLG", 0, 1.905, hidden: true),
            EmitProperty("Value", "PWR_FLAG", 0, 3.81),
            EmitProperty("Footprint", "", 0, 0, hidden: true),
            EmitProperty("Datasheet", "", 0, 0, hidden: true),
            EmitProperty("Description", "Special symbol for telling ERC where power comes from", 0, 0, hidden: true),
            new SList(
                SAtom.Sym("symbol"),
                SAtom.Str("PWR_FLAG_0_0"),
                new SList(
                    SAtom.Sym("pin"),
                    SAtom.Sym("power_out"),
                    SAtom.Sym("line"),
                    new SList(SAtom.Sym("at"), SAtom.Num(0), SAtom.Num(0), SAtom.Num(90)),
                    new SList(SAtom.Sym("length"), SAtom.Num(0)),
                    new SList(SAtom.Sym("name"), SAtom.Str(""),
                        new SList(SAtom.Sym("effects"), new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(1.27), SAtom.Num(1.27))))),
                    new SList(SAtom.Sym("number"), SAtom.Str("1"),
                        new SList(SAtom.Sym("effects"), new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(1.27), SAtom.Num(1.27))))))),
            new SList(
                SAtom.Sym("symbol"),
                SAtom.Str("PWR_FLAG_0_1"),
                new SList(SAtom.Sym("polyline"),
                    new SList(SAtom.Sym("pts"),
                        new SList(SAtom.Sym("xy"), SAtom.Num(0), SAtom.Num(0)),
                        new SList(SAtom.Sym("xy"), SAtom.Num(0), SAtom.Num(1.27)),
                        new SList(SAtom.Sym("xy"), SAtom.Num(-1.016), SAtom.Num(1.905)),
                        new SList(SAtom.Sym("xy"), SAtom.Num(0), SAtom.Num(2.54)),
                        new SList(SAtom.Sym("xy"), SAtom.Num(1.016), SAtom.Num(1.905)),
                        new SList(SAtom.Sym("xy"), SAtom.Num(0), SAtom.Num(1.27))),
                    new SList(SAtom.Sym("stroke"), new SList(SAtom.Sym("width"), SAtom.Num(0)), new SList(SAtom.Sym("type"), SAtom.Sym("default"))),
                    new SList(SAtom.Sym("fill"), new SList(SAtom.Sym("type"), SAtom.Sym("none"))))));
    }

    private void EmitPwrFlagInstance(List<SExpr> sheetItems, string net, SheetLayout layout, string sheetUuid, ref int flagIdx)
    {
        // Park flags well below the sheet's used area in a vertical stack
        // so neither the flag body nor its horizontal label collides with
        // any placed component or another flag. Row pitch is 10.16 mm
        // (4 grid units) - enough vertical clearance for the flag body
        // (~3.5 mm) + the label band (1.27 mm) + 5 mm buffer.
        var ua = layout.UsedArea;
        // PWR_FLAG emits as global_label - has chevron + offset.
        double labelWidth = LabelGeometry.Extent(net, LabelGeometry.Kind.Global);
        // X position: leftmost column, with enough space LEFT for the label
        // (which extends in the -X direction).
        double x = SnapGrid(ua.MinX + labelWidth + 2.0) + _pageCenterX;
        double y = SnapGrid(-ua.MinY + 25.0 + flagIdx * 10.16) + _pageCenterY;
        flagIdx++;

        var node = new List<SExpr>
        {
            SAtom.Sym("symbol"),
            new SList(SAtom.Sym("lib_id"), SAtom.Str("power:PWR_FLAG")),
            new SList(SAtom.Sym("at"), SAtom.Num(x), SAtom.Num(y), SAtom.Num(0)),
            new SList(SAtom.Sym("unit"), SAtom.Sym("1")),
            new SList(SAtom.Sym("body_style"), SAtom.Sym("1")),
            new SList(SAtom.Sym("exclude_from_sim"), SAtom.Sym("no")),
            new SList(SAtom.Sym("in_bom"), SAtom.Sym("no")),
            new SList(SAtom.Sym("on_board"), SAtom.Sym("no")),
            new SList(SAtom.Sym("in_pos_files"), SAtom.Sym("no")),
            new SList(SAtom.Sym("dnp"), SAtom.Sym("no")),
            new SList(SAtom.Sym("fields_autoplaced"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"pwrflag:{sheetUuid}:{net}"))),
            // Hidden - PWR_FLAG body is the visual indicator; the auto-
            // generated #FLG ref and "PWR_FLAG" value would just stomp the
            // body and the adjacent net label.
            EmitProperty("Reference", $"#FLG_{net}", x + 2, y - 2, hidden: true),
            EmitProperty("Value", "PWR_FLAG", x + 2, y - 4, hidden: true),
            EmitProperty("Footprint", "", 0, 0, hidden: true),
            EmitProperty("Datasheet", "", 0, 0, hidden: true),
            new SList(
                SAtom.Sym("pin"),
                SAtom.Str("1"),
                new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"pwrflagpin:{sheetUuid}:{net}")))),
        };

        // Label the pin with the net (global_label so it merges with the rail).
        // Place the global label at the same coordinate so KiCad detects the join.
        // Then the PWR_FLAG's power_out drives that net.
        string pathStr = $"/{_rootUuid}/{sheetUuid}";
        node.Add(new SList(
            SAtom.Sym("instances"),
            new SList(
                SAtom.Sym("project"),
                SAtom.Str(_projectName),
                new SList(
                    SAtom.Sym("path"),
                    SAtom.Str(pathStr),
                    new SList(SAtom.Sym("reference"), SAtom.Str($"#FLG_{net}")),
                    new SList(SAtom.Sym("unit"), SAtom.Sym("1"))))));

        sheetItems.Add(new SList(node));

        // Matching global_label at the same point joins the flag's power_out
        // pin to the named net.
        sheetItems.Add(new SList(
            SAtom.Sym("global_label"),
            SAtom.Str(net),
            new SList(SAtom.Sym("shape"), SAtom.Sym("bidirectional")),
            new SList(SAtom.Sym("at"), SAtom.Num(x), SAtom.Num(y), SAtom.Num(180)),
            new SList(SAtom.Sym("fields_autoplaced"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("effects"),
                new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(1.27), SAtom.Num(1.27))),
                new SList(SAtom.Sym("justify"), SAtom.Sym("right"))),
            new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"pwrflaglbl:{sheetUuid}:{net}")))));
    }

    // -- per-sheet schematic --

    private SExpr EmitSheet(string sheetName, SheetDef sheet, bool asRoot = false)
    {
        _emittedLabels.Clear();
        _coincidentPinNets.Clear();
        BuildCoincidentPinIndex(sheetName, sheet);
        // When flattening, the sheet's UUID *is* the root UUID - the symbol
        // instance paths in this file reference "/<rootUuid>", not a nested
        // "/<rootUuid>/<sheetUuid>" path.
        var sheetUuid = asRoot ? _rootUuid : NewUuid("sheet:" + sheetName);
        var items = new List<SExpr>
        {
            SAtom.Sym("kicad_sch"),
            new SList(SAtom.Sym("version"), SAtom.Sym(KicadVersion)),
            new SList(SAtom.Sym("generator"), SAtom.Str("schgen")),
            new SList(SAtom.Sym("generator_version"), SAtom.Str("10.0")),
            new SList(SAtom.Sym("uuid"), SAtom.Str(sheetUuid)),
            new SList(SAtom.Sym("paper"), SAtom.Str(_doc.Config.PageSize)),
        };
        items.Add(EmitTitleBlock(asRoot ? _doc.Config.Title : sheetName));

        // lib_symbols block: embed every distinct symbol referenced by this
        // sheet so the .kicad_sch is self-contained and renders without
        // depending on the user's sym-lib-table. Derived symbols are
        // flattened — the parent's sub-symbols, pins, and drawings are
        // inlined into the child's body so each embedded symbol stands
        // alone (no cross-symbol extends-resolution at load time).
        var libSymbols = new List<SExpr> { SAtom.Sym("lib_symbols") };
        var seenSymbols = new HashSet<string>(StringComparer.Ordinal);
        foreach (var comp in sheet.Components)
        {
            if (!seenSymbols.Add(comp.Symbol)) continue;
            var sym = _libs.ResolveSymbol(comp.Symbol);
            if (sym is null) continue;
            libSymbols.Add(EmitLibSymbolStub(comp.Symbol, sym));
        }
        // Embed PWR_FLAG so we can flag power nets without a driver.
        var flaggedNets = FlaggedPowerNetsOnSheet(sheetName);
        if (flaggedNets.Count > 0)
            libSymbols.Add(EmitPwrFlagLibSymbol());
        items.Add(new SList(libSymbols));

        // Components (symbol instances) + per-pin labels/NCs.
        if (_placement.Sheets.TryGetValue(sheetName, out var layout))
        {
            foreach (var comp in sheet.Components)
            {
                var placement = layout.FindByRef(comp.Ref, comp.Unit);
                if (placement is null) continue;
                items.Add(EmitSymbolInstance(comp, placement, sheetUuid));
                EmitPinDecorations(items, comp, placement, sheet);
            }
            // Stamp a PWR_FLAG (+ matching global label) per power_net that
            // needs a driver.
            int flagIdx = 1;
            foreach (var net in flaggedNets)
            {
                EmitPwrFlagInstance(items, net, layout, sheetUuid, ref flagIdx);
            }

#if SCHGEN_DEBUG_RECTS
            // DIAGNOSTIC: blue/green outline per fanout rect. Compare schgen's
            // effective-bbox model against the rendered components and spot
            // label/fanout overestimation. Gated by SCHGEN_DEBUG_RECTS.
            EmitFanoutDiagnosticRects(items, layout);
            // DIAGNOSTIC: teal/brown rects around the Reference + Value text
            // per EmitterTextPlacement. Compare against KiCad's actual
            // rendered text to confirm the helper agrees with the emitter.
            EmitRefValueDiagnosticRects(items, sheet, layout);
#endif
        }

        // sheet_instances anchor (required by KiCad 10 for the file to register)
        items.Add(new SList(
            SAtom.Sym("sheet_instances"),
            new SList(SAtom.Sym("path"),
                SAtom.Str("/"),
                new SList(SAtom.Sym("page"), SAtom.Str("1")))));

        items.Add(new SList(SAtom.Sym("embedded_fonts"), SAtom.Sym("no")));

        return new SList(items);
    }

    private SExpr EmitTitleBlock(string sheetName)
    {
        return new SList(
            SAtom.Sym("title_block"),
            new SList(SAtom.Sym("title"), SAtom.Str($"{_doc.Config.Title} - {sheetName}")),
            new SList(SAtom.Sym("rev"), SAtom.Str(_doc.Config.Rev)),
            new SList(SAtom.Sym("company"), SAtom.Str(_doc.Config.Designer)));
    }

    // Embed the source symbol verbatim. Pin coordinates, properties, graphics
    // - all preserved exactly as the upstream library has them, so:
    //   (a) label positions in the schematic line up with pin endpoints, and
    //   (b) "Update Symbols from Library" in eeschema is a no-op rather than
    //       a destructive geometry replacement.
    // The only edit is to the outer head: source has (symbol "Name" ...); the
    // schematic needs (symbol "Lib:Name" ...). For symbols that extend a
    // parent (e.g. `TLV70015_SOT23-5` extends `TLV70012_SOT23-5`), the
    // parent's sub-symbols, pins, and drawings are inlined into the child's
    // body and the `(extends ...)` clause is dropped — yielding a fully
    // self-contained embedded symbol.
    private SList EmitLibSymbolStub(string libColon, SymbolDef sym)
    {
        var lib = libColon.Substring(0, libColon.IndexOf(':'));
        var childClone = (SList)CloneSExpr(sym.RawNode);

        // Non-derived: simple rename of the outer name and we're done.
        if (sym.Extends is null)
        {
            var simple = new List<SExpr>(childClone.Items.Count) { childClone.Items[0] };
            simple.Add(SAtom.Str(libColon));
            for (int i = 2; i < childClone.Items.Count; i++) simple.Add(childClone.Items[i]);
            return new SList(simple);
        }

        // Derived: pull the parent's sub-symbols + drawings, rename them
        // from <ParentBase>_<u>_<style> to <ChildBase>_<u>_<style> (KiCad
        // requires sub-symbol names to share the outer symbol's bare base),
        // and append them to the child's body. Properties already on the
        // child override the parent's verbatim.
        var parent = _libs.ResolveSymbol($"{lib}:{sym.Extends}");
        if (parent is null)
        {
            // No parent available - emit child as-is (loader's
            // ResolveExtends already populated pins, so placer/labels
            // still work; KiCad may complain about the dangling extends).
            var fallback = new List<SExpr>(childClone.Items.Count) { childClone.Items[0] };
            fallback.Add(SAtom.Str(libColon));
            for (int i = 2; i < childClone.Items.Count; i++) fallback.Add(childClone.Items[i]);
            return new SList(fallback);
        }

        var parentClone = (SList)CloneSExpr(parent.RawNode);
        var childBaseName = sym.Name;
        var parentBaseName = parent.Name;

        var flattened = new List<SExpr> { childClone.Items[0], SAtom.Str(libColon) };
        // Keep child's properties (Reference / Value / Footprint / Datasheet
        // / Description / keywords / filters / embedded_fonts) - they're
        // the overrides whose existence justifies the extends in the first
        // place. Drop the (extends ...) clause itself.
        var childPropertyKeys = new HashSet<string>(StringComparer.Ordinal);
        for (int i = 2; i < childClone.Items.Count; i++)
        {
            var item = childClone.Items[i];
            if (item is SList sl && sl.Head == "extends") continue;
            flattened.Add(item);
            if (item is SList propSl && propSl.Head == "property"
                && propSl.Items.Count >= 2 && propSl.Items[1] is SAtom k)
            {
                childPropertyKeys.Add(k.Value);
            }
        }
        // Inline parent's content. Skip parent's outer name + duplicated
        // property entries the child already provides. Rename any
        // sub-symbol (nested `(symbol ...)`) name so it parents under the
        // child's base name.
        for (int i = 2; i < parentClone.Items.Count; i++)
        {
            var item = parentClone.Items[i];
            if (item is SList sl)
            {
                if (sl.Head == "property" && sl.Items.Count >= 2
                    && sl.Items[1] is SAtom pk
                    && childPropertyKeys.Contains(pk.Value))
                {
                    continue;
                }
                if (sl.Head == "symbol" && sl.Items.Count >= 2
                    && sl.Items[1] is SAtom subNameAtom)
                {
                    // KiCad sub-symbol names follow `<base>_<u>_<style>`.
                    // Substitute parent base with child base to preserve
                    // the unit / style suffix.
                    var newName = subNameAtom.Value.StartsWith(parentBaseName + "_", StringComparison.Ordinal)
                        ? childBaseName + subNameAtom.Value.Substring(parentBaseName.Length)
                        : subNameAtom.Value;
                    var renamedSub = new List<SExpr>(sl.Items.Count) { sl.Items[0], SAtom.Str(newName) };
                    for (int j = 2; j < sl.Items.Count; j++) renamedSub.Add(sl.Items[j]);
                    flattened.Add(new SList(renamedSub));
                    continue;
                }
                // embedded_fonts in parent: skip if child already has one.
                if (sl.Head == "embedded_fonts" && childPropertyKeys.Contains("embedded_fonts"))
                    continue;
            }
            flattened.Add(item);
        }
        return new SList(flattened);
    }

    private static SExpr CloneSExpr(SExpr node) => node switch
    {
        SAtom a => new SAtom(a.Value, a.Quoted),
        SList l => new SList(l.Items.Select(CloneSExpr).ToList()),
        _       => throw new InvalidOperationException($"unknown SExpr type {node.GetType()}"),
    };

    private SList EmitSymbolInstance(ComponentDef comp, ComponentPlacement p, string sheetUuid)
    {
        // Symbol anchor in emit coords = placer's (p.X, p.Y) shifted by the
        // page centre and Y-flipped. NO per-symbol UnitBBox.CenterX shift -
        // adding one would re-anchor each symbol at its lib bbox centre,
        // which differs per symbol (e.g. RK3566 unit 3 has CenterX=+60mm
        // because pins extend far right of the lib origin) and silently
        // breaks the placer's relative-position math: two symbols the
        // placer thinks are 2 mm apart end up |DCenterX| mm closer or
        // farther apart in the emitted schematic.
        var node = new List<SExpr>
        {
            SAtom.Sym("symbol"),
            new SList(SAtom.Sym("lib_id"), SAtom.Str(comp.Symbol)),
            new SList(SAtom.Sym("at"),
                SAtom.Num(p.X + _pageCenterX),
                SAtom.Num(-p.Y + _pageCenterY),
                SAtom.Num(p.Rotation)),
            new SList(SAtom.Sym("unit"), SAtom.Sym(comp.Unit.ToString())),
            new SList(SAtom.Sym("body_style"), SAtom.Sym("1")),
            new SList(SAtom.Sym("exclude_from_sim"), SAtom.Sym("no")),
            new SList(SAtom.Sym("in_bom"), SAtom.Sym(comp.Dnp ? "no" : "yes")),
            new SList(SAtom.Sym("on_board"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("in_pos_files"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("dnp"), SAtom.Sym(comp.Dnp ? "yes" : "no")),
            // fields_autoplaced=no so KiCad respects our explicit Reference/
            // Value text positions instead of re-running its own autoplace
            // (which composes parent rotation into the text orientation and
            // ignores our (at X Y) coords).
            new SList(SAtom.Sym("fields_autoplaced"), SAtom.Sym("no")),
            new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"comp:{sheetUuid}:{comp.Ref}#{comp.Unit}"))),
        };

        // Use the EmitterTextPlacement helper so the diagnostic rect
        // emitter (which uses the same helper) and the property emit
        // cannot disagree. The helper returns rects in placer Y-up
        // frame; convert to KiCad's Y-down screen frame here.
        var bodyBBox = Placement.EmitterTextPlacement.BodyBoxInPlacerCoords(
            p.Symbol, comp.Unit, p.Rotation, p.X, p.Y);
        var refRect = Placement.EmitterTextPlacement.ReferenceTextRect(comp, bodyBBox, p.Rotation);
        var valRect = Placement.EmitterTextPlacement.ValueTextRect(comp, p.Symbol, bodyBBox, p.Rotation);

        double refX = (refRect.MinX + refRect.MaxX) * 0.5 + _pageCenterX;
        double refY = -(refRect.MinY + refRect.MaxY) * 0.5 + _pageCenterY;
        double valX = (valRect.MinX + valRect.MaxX) * 0.5 + _pageCenterX;
        double valY = -(valRect.MinY + valRect.MaxY) * 0.5 + _pageCenterY;

        // Property text rotation: KiCad 10 renders text glyph at
        // (parent_symbol_rotation + property_rotation) mod 360 for
        // parent 90/270, and treats property rotation as ABSOLUTE for
        // parent 0/180. To get horizontal text at every parent rotation:
        //   0   -> 0   (already horizontal)
        //   90  -> 270 (composes to 0)
        //   180 -> 0   (absolute, so 0 means horizontal)
        //   270 -> 90  (composes to 0)
        int parentRot = ((int)Math.Round(p.Rotation) % 360 + 360) % 360;
        int propRot = parentRot switch {
            90 => 270,
            270 => 90,
            _ => 0,
        };

        node.Add(EmitProperty("Reference", comp.Ref, refX, refY, rot: propRot));
        node.Add(EmitProperty("Value",     comp.Value ?? "", valX, valY, rot: propRot));
        node.Add(EmitProperty("Footprint", comp.Footprint, refX, refY, hidden: true));
        node.Add(EmitProperty("Datasheet", comp.Datasheet ?? "", refX, refY, hidden: true));
        node.Add(EmitProperty("Description", "", refX, refY, hidden: true));

        if (!string.IsNullOrEmpty(comp.Mpn))           node.Add(EmitProperty("MPN", comp.Mpn, refX, refY, hidden: true));
        if (!string.IsNullOrEmpty(comp.Manufacturer))  node.Add(EmitProperty("Manufacturer", comp.Manufacturer, refX, refY, hidden: true));
        if (!string.IsNullOrEmpty(comp.Tolerance))     node.Add(EmitProperty("Tolerance", comp.Tolerance, refX, refY, hidden: true));
        if (!string.IsNullOrEmpty(comp.Voltage))       node.Add(EmitProperty("Voltage", comp.Voltage, refX, refY, hidden: true));

        // One (pin "N" (uuid ...)) per pin OF THIS UNIT only - KiCad
        // expects the per-instance pin list to match the unit's own pins.
        foreach (var pin in p.Symbol.PinsOfUnit(comp.Unit).OrderBy(pp => pp.Number, StringComparer.Ordinal))
        {
            node.Add(new SList(
                SAtom.Sym("pin"),
                SAtom.Str(pin.Number),
                new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"pin:{sheetUuid}:{comp.Ref}#{comp.Unit}:{pin.Number}")))));
        }

        // (instances (project "<name>" (path "/<sheetUuid>" (reference "U1") (unit N))))
        string pathStr = sheetUuid == _rootUuid ? $"/{sheetUuid}" : $"/{_rootUuid}/{sheetUuid}";
        node.Add(new SList(
            SAtom.Sym("instances"),
            new SList(
                SAtom.Sym("project"),
                SAtom.Str(_projectName),
                new SList(
                    SAtom.Sym("path"),
                    SAtom.Str(pathStr),
                    new SList(SAtom.Sym("reference"), SAtom.Str(comp.Ref)),
                    new SList(SAtom.Sym("unit"), SAtom.Sym(comp.Unit.ToString()))))));

        return new SList(node);
    }

    /// Track (x, y, net) already emitted per sheet so duplicate co-located
    /// labels (e.g. host pin + attached passive's host-side pin landing at
    /// the same point) only emit once.
    private readonly HashSet<(long, long, string)> _emittedLabels = new();

    /// (x, y, net) -> number of DISTINCT COMPONENTS that have a pin endpoint
    /// at that exact world coord on this net. When the count is > 1, multiple
    /// components are physically coincident, KiCad treats them as directly
    /// connected, and we SUPPRESS the label there - emitting one would force
    /// the text across one of the adjoining component bodies. Same-component
    /// stacked pins (KiCad's convention for multi-ball power pins like
    /// TLV62080's stacked GNDs) do NOT trigger suppression - we want one
    /// label for the stack so ERC sees the connection.
    private readonly Dictionary<(long, long, string), int> _coincidentPinNets = new();

    private void BuildCoincidentPinIndex(string sheetName, SheetDef sheet)
    {
        if (!_placement.Sheets.TryGetValue(sheetName, out var layout)) return;
        // (coord, net) -> set of distinct component keys with a pin there.
        var ownersByKey = new Dictionary<(long, long, string), HashSet<string>>();
        foreach (var comp in sheet.Components)
        {
            var placement = layout.FindByRef(comp.Ref, comp.Unit);
            if (placement is null) continue;
            double symX = placement.X + _pageCenterX;
            double symY = -placement.Y + _pageCenterY;
            double compRad = placement.Rotation * Math.PI / 180.0;
            double cos = Math.Cos(compRad), sin = Math.Sin(compRad);
            string ownerKey = $"{comp.Ref}#{comp.Unit}";
            foreach (var pin in placement.Symbol.PinsOfUnit(comp.Unit))
            {
                List<string>? nets = null;
                if (comp.Pins.TryGetValue(pin.Number, out var byNum)) nets = byNum;
                else if (comp.Pins.TryGetValue(pin.Name, out var byName)) nets = byName;
                if (nets is null) continue;
                double rx = pin.X * cos - pin.Y * sin;
                double ry = pin.X * sin + pin.Y * cos;
                double px = symX + rx;
                double py = symY - ry;
                var (kx, ky) = LabelKey(px, py);
                foreach (var net in nets)
                {
                    if (string.IsNullOrEmpty(net) || net == "NC") continue;
                    var key = (kx, ky, net);
                    if (!ownersByKey.TryGetValue(key, out var owners))
                        ownersByKey[key] = owners = new HashSet<string>(StringComparer.Ordinal);
                    owners.Add(ownerKey);
                }
            }
        }
        // Materialize as a count of distinct owners. The label-emit gate
        // uses this count: > 1 means a cross-component coincidence and
        // suppresses the label; == 1 means same-component stacked pins
        // and the label is emitted normally.
        foreach (var (key, owners) in ownersByKey)
            _coincidentPinNets[key] = owners.Count;
    }

    private static (long, long) LabelKey(double x, double y) =>
        // 0.01 mm precision (the schematic's coord precision).
        ((long)Math.Round(x * 100.0), (long)Math.Round(y * 100.0));

    private void EmitPinDecorations(
        List<SExpr> sheetItems,
        ComponentDef comp,
        ComponentPlacement p,
        SheetDef sheet)
    {
        // For each pin on the symbol: write either a label/global-label/hier-label
        // matching its YAML net (if listed and not NC), OR a no_connect marker
        // (if not listed or net is NC).
        bool isTemplate = sheet.Template;
        // Symbol library uses y-up; KiCad schematic uses y-down. The symbol's
        // `(at sx sy rot)` rotates the lib geometry by `rot` (math CCW in lib
        // coords) THEN flips Y for screen. Labels must land exactly on the
        // rotated + flipped pin endpoint for KiCad to register the connection.
        double symX = p.X + _pageCenterX;
        double symY = -p.Y + _pageCenterY;
        double compRad = p.Rotation * Math.PI / 180.0;
        double compCos = Math.Cos(compRad);
        double compSin = Math.Sin(compRad);
        foreach (var pin in p.Symbol.PinsOfUnit(comp.Unit))
        {
            // Rotate the lib pin coord by the symbol rotation (math CCW in
            // lib y-up), then apply the Y-flip for the schematic.
            double rx = pin.X * compCos - pin.Y * compSin;
            double ry = pin.X * compSin + pin.Y * compCos;
            double px = symX + rx;
            double py = symY - ry;

            // Lookup the YAML nets for this pin (list - first is canonical
            // electrical, rest are schematic-only tag labels).
            List<string>? nets = null;
            if (comp.Pins.TryGetValue(pin.Number, out var byNum)) nets = byNum;
            else if (comp.Pins.TryGetValue(pin.Name, out var byName)) nets = byName;

            bool isNc = nets is null || nets.Count == 0
                        || nets.All(n => string.IsNullOrEmpty(n) || n == "NC");
            if (isNc)
            {
                sheetItems.Add(new SList(
                    SAtom.Sym("no_connect"),
                    new SList(SAtom.Sym("at"), SAtom.Num(px), SAtom.Num(py)),
                    new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"nc:{comp.Ref}#{comp.Unit}:{pin.Number}")))));
                continue;
            }

            // Emit one label per declared net (filtering NC). Multi-net pins
            // produce stacked labels at the same world coord; KiCad merges
            // them electrically via shared anchor point.
            int labelRot = LabelRotationFor(pin.Rotation, p.Rotation);
            string justify = JustifyForLabelRotation(labelRot);
            foreach (var net in nets!)
            {
                if (string.IsNullOrEmpty(net) || net == "NC") continue;

                // Label type promotion rules:
                //   1. Template port -> hierarchical_label (sheet-pin contract)
                //   2. Flagged for PWR_FLAG -> global_label (PWR_FLAG itself
                //      emits a global label, so the pin must match for KiCad
                //      to merge electrically)
                //   3. Net used on multiple sheets -> global_label
                //   4. Otherwise -> local label
                // Power nets that are only used on a single sheet (and have a
                // driver, so no PWR_FLAG) now stay LOCAL - visually cleaner,
                // and same electrical behaviour within the sheet.
                string head;
                if (isTemplate && sheet.Ports.ContainsKey(net))
                    head = "hierarchical_label";
                else if (_flaggedNets.Contains(net))
                    head = "global_label";
                else if (_instanceCounts.GetValueOrDefault(sheet.Name, 0) <= 1
                         && IsNetCrossSheet(net, sheet.Name))
                    head = "global_label";
                else
                    head = "label";

                var (kx, ky) = LabelKey(px, py);
                if (!_emittedLabels.Add((kx, ky, net))) continue;
                // Two or more pin endpoints coincide here on this net -
                // KiCad treats them as electrically connected. Emitting
                // a label would force the text across one of the
                // adjoining component bodies, so skip it.
                if (_coincidentPinNets.GetValueOrDefault((kx, ky, net)) > 1) continue;

                var labelNode = new List<SExpr> { SAtom.Sym(head), SAtom.Str(net) };
                if (head == "hierarchical_label")
                    labelNode.Add(new SList(SAtom.Sym("shape"), SAtom.Sym(PortShape(sheet, net))));
                else if (head == "global_label")
                    labelNode.Add(new SList(SAtom.Sym("shape"), SAtom.Sym("bidirectional")));
                labelNode.Add(new SList(SAtom.Sym("at"), SAtom.Num(px), SAtom.Num(py), SAtom.Num(labelRot)));
                labelNode.Add(new SList(SAtom.Sym("fields_autoplaced"), SAtom.Sym("yes")));
                // Stub labels that share their pin with another (non-stub) net
                // get rendered at a tiny font (0.4 mil = 0.01 mm) so they're
                // visually invisible while still carrying KiCad's name-based
                // connectivity. KiCad's (hide yes) attribute doesn't work on
                // labels (only on Property fields). Single-net pins keep the
                // normal font - their stub label is the pin's only on-screen
                // identifier.
                bool isMultiNetStub = nets!.Count >= 2 && _doc.GeneratedStubNets.Contains(net);
                double fontSize = isMultiNetStub ? 0.01 : 1.27;
                labelNode.Add(new SList(SAtom.Sym("effects"),
                    new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(fontSize), SAtom.Num(fontSize))),
                    new SList(SAtom.Sym("justify"), SAtom.Sym(justify))));
                labelNode.Add(new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"lbl:{comp.Ref}#{comp.Unit}:{pin.Number}:{net}"))));
                sheetItems.Add(new SList(labelNode));

#if SCHGEN_DEBUG_RECTS
                // DIAGNOSTIC: per-label cyan/orange/red/magenta rects showing
                // text / padding / chevron components. Stub labels (tiny
                // hidden font) are skipped - they're not user-visible.
                if (!isMultiNetStub)
                {
                    var kind = head == "global_label"        ? Placement.LabelGeometry.Kind.Global
                            : head == "hierarchical_label"  ? Placement.LabelGeometry.Kind.Hierarchical
                            :                                  Placement.LabelGeometry.Kind.Regular;
                    EmitLabelDebugRects(sheetItems, px, py, labelRot, net, kind);
                }
#endif
            }
        }
    }

    /// Label rotation for KiCad 10, accounting for the Y-flip between the
    /// placer (Y-up math frame) and the schematic emit (Y-down screen frame).
    ///
    /// `pin_world_dir = (sym_pin_rot + comp_rot) % 360` is the pin's body
    /// direction in placer/lib frame. The label extends outward (opposite of
    /// the body direction). In a Y-up frame the outward direction is
    /// (pin_world_dir + 180), but flipping to Y-down inverts the vertical
    /// component of the rotation, giving `(180 - pin_world_dir)`. The two
    /// formulas agree for horizontal pins (pin_world_dir ∈ {0, 180}) and
    /// swap 90 ↔ 270 for vertical pins - matching KiCad 10's actual rendering.
    private static int LabelRotationFor(double symPinRot, double compRot)
    {
        int pinWorldDir = (((int)Math.Round(symPinRot + compRot)) % 360 + 360) % 360;
        return ((pinWorldDir + 180) % 360 + 360) % 360;
    }

    /// Per the canonical correct-justify-for-rotation table: rotations 0 / 90
    /// pair with left justify; 180 / 270 with right.
    private static string JustifyForLabelRotation(int labelRot) =>
        labelRot is 0 or 90 ? "left" : "right";

    private static string PortShape(SheetDef sheet, string portName) =>
        sheet.Ports.TryGetValue(portName, out var p) ? p.Dir switch
        {
            "input"     => "input",
            "output"    => "output",
            "bidir"     => "bidirectional",
            "power_in"  => "input",
            "power_out" => "output",
            _           => "passive",
        } : "input";

    private bool IsNetCrossSheet(string net, string thisSheet)
    {
        if (!_nets.TryGetValue(net, out var ends)) return false;
        foreach (var e in ends)
            if (e.Sheet != thisSheet) return true;
        return false;
    }

    // -- root sheet --

    private SExpr EmitRoot(string projectName)
    {
        var items = new List<SExpr>
        {
            SAtom.Sym("kicad_sch"),
            new SList(SAtom.Sym("version"), SAtom.Sym(KicadVersion)),
            new SList(SAtom.Sym("generator"), SAtom.Str("schgen")),
            new SList(SAtom.Sym("generator_version"), SAtom.Str("10.0")),
            new SList(SAtom.Sym("uuid"), SAtom.Str(_rootUuid)),
            new SList(SAtom.Sym("paper"), SAtom.Str(_doc.Config.PageSize)),
        };
        items.Add(EmitTitleBlock("Root"));

        // Empty lib_symbols (children carry theirs).
        items.Add(new SList(SAtom.Sym("lib_symbols")));

        // Place sheet blocks in a grid that fits the configured page size.
        // Sheets are sized large enough for KiCad to render their hierarchical
        // pins without overlapping neighbours.
        const double sheetW = 80, sheetH = 60, gapX = 20, gapY = 25, marginX = 20, marginY = 30;
        (double pageW, double pageH) = PageDims(_doc.Config.PageSize);
        int cols = Math.Max(1, (int)Math.Floor((pageW - 2 * marginX + gapX) / (sheetW + gapX)));
        double x = marginX, y = marginY;
        int col = 0;
        int pageNo = 2;
        var pages = new List<(string path, int page)> { ("/", 1) };
        _pendingSheetLabels.Clear();
        foreach (var inst in _doc.Root.Instantiate)
        {
            var sheetName = inst.Sheet;
            if (!_doc.Sheets.TryGetValue(sheetName, out var sheetDef)) continue;
            var (sheetBlock, sheetUuid) = EmitSheetInstance(inst, sheetDef, x, y, sheetW, sheetH);
            items.Add(sheetBlock);
            pages.Add(($"/{sheetUuid}", pageNo++));
            col++;
            if (col >= cols)
            {
                col = 0;
                x = marginX;
                y += sheetH + gapY;
            }
            else
            {
                x += sheetW + gapX;
            }
        }
        // Sibling global labels created by sheet-pin remapping go here.
        items.AddRange(_pendingSheetLabels);
        _pendingSheetLabels.Clear();

        // sheet_instances enumerates every sheet path (including root).
        var siChildren = new List<SExpr> { SAtom.Sym("sheet_instances") };
        foreach (var (path, page) in pages)
        {
            siChildren.Add(new SList(
                SAtom.Sym("path"),
                SAtom.Str(path),
                new SList(SAtom.Sym("page"), SAtom.Str(page.ToString()))));
        }
        items.Add(new SList(siChildren));

        items.Add(new SList(SAtom.Sym("embedded_fonts"), SAtom.Sym("no")));

        return new SList(items);
    }

    private (SList block, string sheetUuid) EmitSheetInstance(SheetInstance inst, SheetDef sheetDef, double x, double y, double w, double h)
    {
        var fileName = $"{inst.Sheet}.kicad_sch";
        // Match the sub-sheet's own UUID so the path "/<rootUuid>/<sheetUuid>"
        // lines up with the symbol-instance paths inside the sub-sheet.
        var sheetUuid = NewUuid("sheet:" + inst.Sheet);
        var node = new List<SExpr>
        {
            SAtom.Sym("sheet"),
            new SList(SAtom.Sym("at"), SAtom.Num(x), SAtom.Num(y)),
            new SList(SAtom.Sym("size"), SAtom.Num(w), SAtom.Num(h)),
            new SList(SAtom.Sym("exclude_from_sim"), SAtom.Sym("no")),
            new SList(SAtom.Sym("in_bom"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("on_board"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("dnp"), SAtom.Sym("no")),
            new SList(SAtom.Sym("fields_autoplaced"), SAtom.Sym("yes")),
            new SList(SAtom.Sym("stroke"), new SList(SAtom.Sym("width"), SAtom.Num(0.1524)), new SList(SAtom.Sym("type"), SAtom.Sym("solid"))),
            new SList(SAtom.Sym("fill"), new SList(SAtom.Sym("color"), SAtom.Sym("0"), SAtom.Sym("0"), SAtom.Sym("0"), SAtom.Sym("0.0000"))),
            new SList(SAtom.Sym("uuid"), SAtom.Str(sheetUuid)),
            EmitProperty("Sheetname", inst.EffectiveName, x, y - 1),
            EmitProperty("Sheetfile", fileName, x, y + h + 1),
        };

        // Sheet pin name MUST equal the matching hierarchical label inside
        // the sheet (the port name). The instance-specific net comes from
        // a sibling global_label placed at the same coordinate so KiCad
        // merges them.
        var siblingLabels = new List<SExpr>();
        if (sheetDef.Template)
        {
            double py = y;
            foreach (var (portName, port) in sheetDef.Ports)
            {
                var net = inst.Params.TryGetValue(portName, out var p) ? p : portName;
                node.Add(new SList(
                    SAtom.Sym("pin"),
                    SAtom.Str(portName),
                    SAtom.Sym(port.Dir switch
                    {
                        "input"     => "input",
                        "output"    => "output",
                        "bidir"     => "bidirectional",
                        "power_in"  => "input",
                        "power_out" => "output",
                        _           => "passive",
                    }),
                    new SList(SAtom.Sym("at"), SAtom.Num(x), SAtom.Num(py), SAtom.Num(180)),
                    new SList(SAtom.Sym("effects"),
                        new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(1.27), SAtom.Num(1.27))),
                        new SList(SAtom.Sym("justify"), SAtom.Sym("right"))),
                    new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"sheetpin:{inst.EffectiveName}:{portName}")))));

                // Always emit a sibling global label at the sheet pin so it
                // joins the rail electrically - KiCad treats an unwired
                // sheet pin as a floating connection.
                siblingLabels.Add(new SList(
                    SAtom.Sym("global_label"),
                    SAtom.Str(net),
                    new SList(SAtom.Sym("shape"), SAtom.Sym("bidirectional")),
                    new SList(SAtom.Sym("at"), SAtom.Num(x), SAtom.Num(py), SAtom.Num(180)),
                    new SList(SAtom.Sym("fields_autoplaced"), SAtom.Sym("yes")),
                    new SList(SAtom.Sym("effects"),
                        new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(1.27), SAtom.Num(1.27))),
                        new SList(SAtom.Sym("justify"), SAtom.Sym("right"))),
                    new SList(SAtom.Sym("uuid"), SAtom.Str(NewUuid($"sheetpinlbl:{inst.EffectiveName}:{portName}")))));
                py += 2.54;
            }
        }

        _pendingSheetLabels.AddRange(siblingLabels);
        return (new SList(node), sheetUuid);
    }

    // -- shared helpers --

    private SList EmitProperty(string key, string value, double x, double y, bool hidden = false, int rot = 0, string? justify = null)
    {
        var items = new List<SExpr>
        {
            SAtom.Sym("property"),
            SAtom.Str(key),
            SAtom.Str(value),
            new SList(SAtom.Sym("at"), SAtom.Num(x), SAtom.Num(y), SAtom.Num(rot)),
        };
        if (hidden) items.Add(new SList(SAtom.Sym("hide"), SAtom.Sym("yes")));
        var effects = new List<SExpr>
        {
            SAtom.Sym("effects"),
            new SList(SAtom.Sym("font"), new SList(SAtom.Sym("size"), SAtom.Num(1.27), SAtom.Num(1.27))),
        };
        // KiCad defaults to CENTER alignment when no justify is set. The
        // helper EmitterTextPlacement.ReferenceTextRect / ValueTextRect
        // assume LEFT or RIGHT anchor (depending on text placement intent),
        // so emit an explicit justify here so the rendered text occupies
        // the same rect the placer reserved.
        if (justify is not null)
            effects.Add(new SList(SAtom.Sym("justify"), SAtom.Sym(justify)));
        items.Add(new SList(effects));
        return new SList(items);
    }

    private static double SnapGrid(double v) => Math.Round(v / 2.54) * 2.54;

    /// Extract "Lib" from a "Lib:Name" lib_id string. Null if malformed.
    private static string? LibNickname(string libColonName)
    {
        var i = libColonName.IndexOf(':');
        return i > 0 ? libColonName[..i] : null;
    }

    /// Page dimensions in mm for the standard KiCad paper sizes.
    /// Defaults to A4 if the config value is unrecognized.
    private static (double width, double height) PageDims(string size) => size.ToUpperInvariant() switch
    {
        "A0" => (1189, 841),
        "A1" => (841, 594),
        "A2" => (594, 420),
        "A3" => (420, 297),
        "A4" => (297, 210),
        "A5" => (210, 148),
        "USLEDGER" => (432, 279),
        "USLEGAL"  => (356, 216),
        "USLETTER" => (279, 216),
        _    => (297, 210),
    };

    /// True if the symbol has any pin whose endpoint sits at (or near) the
    /// lib y-up MinY - i.e. it sticks out the bottom of the bbox. Used to
    /// pick Value placement: bottom-center if no bottom pin, bottom-right
    /// otherwise so the Value text doesn't crash into the pin's label.
    private static bool HasPinAtBottom(SymbolDef sym)
    {
        if (sym.Pins.Count == 0) return false;
        double lowestPinY = sym.Pins.Min(p => p.Y);
        return Math.Abs(lowestPinY - sym.BoundingBox.MinY) < 0.01;
    }

    private static string SafeIdent(string s) =>
        new string(s.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());

    private static string NewUuid(string seed)
    {
        // Deterministic UUID from seed so re-runs produce byte-identical output.
        // Use MD5 hash -> 16 bytes -> format as KiCad-style UUID.
        using var md5 = System.Security.Cryptography.MD5.Create();
        var bytes = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes("schgen:" + seed));
        // Set version (4) and variant (RFC 4122) bits for prettiness.
        bytes[6] = (byte)((bytes[6] & 0x0F) | 0x40);
        bytes[8] = (byte)((bytes[8] & 0x3F) | 0x80);
        return string.Format(CultureInfo.InvariantCulture,
            "{0:x2}{1:x2}{2:x2}{3:x2}-{4:x2}{5:x2}-{6:x2}{7:x2}-{8:x2}{9:x2}-{10:x2}{11:x2}{12:x2}{13:x2}{14:x2}{15:x2}",
            bytes[0], bytes[1], bytes[2], bytes[3], bytes[4], bytes[5], bytes[6], bytes[7],
            bytes[8], bytes[9], bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15]);
    }

}
