namespace Schgen.Core.KiCad;

/// Project-file emit: writes the `.kicad_pro` JSON and the `sym-lib-table`
/// that lists the stock symbol libraries schgen resolved against but didn't
/// embed. Split out as a partial so the main `SchematicEmitter` file stays
/// focused on `.kicad_sch` content.
public sealed partial class SchematicEmitter
{
    private string EmitSymLibTable()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("(sym_lib_table");
        sb.AppendLine("\t(version 7)");
        // Stock libs schgen resolved during the build but didn't embed.
        var stockNicks = _libs.SymbolLibraryNicknames
            .Where(n => !_libs.IsProjectSymbolLib(n))
            .OrderBy(n => n, StringComparer.Ordinal);
        foreach (var nick in stockNicks)
        {
            sb.AppendLine($"\t(lib (name \"{nick}\") (type \"KiCad\") " +
                          $"(uri \"${{KICAD10_SYMBOL_DIR}}/{nick}.kicad_symdir\") " +
                          $"(options \"\") (descr \"\"))");
        }
        sb.AppendLine(")");
        return sb.ToString();
    }

    private string EmitProject(string projectName)
    {
        // Minimal .kicad_pro JSON that KiCad 10 accepts. The ERC severities
        // silence the `lib_symbol_mismatch` warning that fires whenever an
        // embedded symbol differs from a same-named entry in the user's global
        // symbol library table (which it always will, since schgen embeds
        // exactly the source library version regardless of what's installed
        // globally). Schematics are regenerated by re-running `schgen build`,
        // not by clicking "Update Symbols from Library" in eeschema, so this
        // warning has no useful signal here.
        return $$"""
            {
              "board": {
                "design_settings": {
                  "rule_severities": {
                    "lib_footprint_issues": "ignore",
                    "lib_footprint_mismatch": "ignore"
                  }
                }
              },
              "boards": [],
              "cvpcb": { "equivalence_files": [] },
              "erc": {
                "rule_severities": {
                  "lib_symbol_issues": "ignore",
                  "lib_symbol_mismatch": "ignore",
                  "footprint_link_issues": "ignore",
                  "pin_to_pin": "ignore",
                  "pin_not_driven": "ignore"
                }
              },
              "libraries": { "pinned_footprint_libs": [], "pinned_symbol_libs": [] },
              "meta": { "filename": "{{projectName}}.kicad_pro", "version": 1 },
              "net_settings": { "classes": [ { "name": "Default" } ] },
              "pcbnew": { "page_layout_descr_file": "" },
              "schematic": {
                "annotate_start_num": 0,
                "drawing": {},
                "legacy_lib_dir": "",
                "legacy_lib_list": [],
                "meta": { "version": 1 },
                "page_layout_descr_file": "",
                "ngspice": {},
                "spice_external_command": "spice \"%I\""
              },
              "sheets": [],
              "text_variables": {}
            }
            """;
    }
}
